### ISSUE TITLE
Coding System issue (fixed) and aditional tools.

### ISSUE THREAD

**Issue by hatschipuh** [sshbio/drawille#1]
Hi,

The Braille characters in the comments messed up in my buffer and the coding system couldn't be detected. I deleted them and now it works. I'm not sure if I did something wrong? What coding system do you use?

**Comment by sshbio** [comment]
My system is in UTF-8 locale, and my implementation is based on unicode: It goes to the position of the first Unicode braille character, and use the functions to find the corresponding next Unicode braille characters.

This function transform the unicode position (a number) to a string: `char-to-string`.  So the first unicode braille character is expected to be:

```elisp
(char-to-string #x2800)
```

This returns "⠀" to me (empty unicode char).

#x2800 is an hexadecimal number, corresponding to the position of the first unicode character.

```elisp
(char-to-string #x2801)
```
Returns "⠁" to me (1 filled)
#x2802 - > "⠂" (2 filled)
#x2803 -> "⠃" (1 and 2 filled)
And so on...

This is how drawille.el returns the the character to display: corresponding Unicode index.
Is it working for you?

It could be helping if you could share some string or matrix you were converting.

**Comment by hatschipuh** [comment]
No sorry you misunderstood, I had a problem with the braille characters that were in the commentary. The rest works fine :) 
I tried some animation of a sinus curve like in the original python version, but it was a little bit too slow. Have you successfully tried any animations yet?

**Comment by sshbio** [comment]
I had problem as well, so I removed them.  It may have been due to github editor.
Now that I am aware of it, I will avoid it.

No, I did not make any animation with it, and would really apreciate if you show me what you did!  I also read from @wasamasa that he was curious about a way to make animations with it.

What could be done is processing the whole animation at first, and then display it (if it is a loop, as an example).  I will have a look at how is the python version implemented...

Thank you for your remarks!

**Comment by sshbio** [comment]
It seems that the original Drawille is updating a portion of a canvas rather that recreating everything at each frame.  An advantage of my method is that anything that can operate on a vector can edit operate on the Drawille representation, but this do not permit as good performances as it should.

Providing good functions instead of letting the user edit matrices to get the desired effects may permit an improvement in the performances.

**Comment by hatschipuh** [comment]
On my second try I collected the strings first and then used this list of strings for the animation. At the moment there is nothing of interest I could show you, I just created some sine function plots each shifted further to the left and then looped through the list erasing the buffer and inserting the plots.

It would be nice to have some user options for creating plots in an easier manner. I will try some more things this week and will post them here, but don't expect to much I'm just a hobby programmer who likes playing with Emacs...

When trying to make the plot fullscreen I noticed something strange: 
If I check the column in the plot with `M-x current-column` it shows me a different number than if I check the column if I'm outside of the plot (where some text is inserted).  Do you have an idea why this happens?

**Comment by wasamasa** [comment]
I've battled with a similiar problem with [Retris](https://github.com/wasamasa/retris).  It has an internal representation of the game grid (vector of vectors of chars) and an external representation (a XPM string) which I regularly delete from and insert into a buffer.  The bottleneck for me was modifying every part of the string to take the desired form although only a few parts of it needed to be updated.  I solved this initially by figuring out manually what parts to change, then later wrote a function comparing two game states and figuring out the changes.  Another function applies these changes to a string and that works nicely.  Then I've refined it with a flag that decides on whether the changes shall be calculated and drawn as I was using a 60fps timer and didn't want to check on every frame, only when a group of game-relevant actions happened.  This allowed me to compose changes to the game state and display these afterwards.

I'm not sure how useful this is for your project.  I'm using a similiarly stupid approach for the ASCII version of [zone-nyan](https://github.com/wasamasa/zone-nyan) and noticed it performs significantly better in a terminal than GUI Emacs.  Most likely because the terminal version tries similiar optimizations to minimize redrawing.  Whether it's worth reimplementing this for a library is questionable at best.

**Comment by sshbio** [comment]
@hatschipuh: Even if these will be simple hings, they may not be the way I would have imagined, and would then bring more ideas on how to implement these.  I'm a hobby programmer as well: biology student.

This library definitely needs functions to [draw] https://github.com/asciimoo/drawille/blob/master/drawille.py#L116) or [clear](https://github.com/asciimoo/drawille/blob/master/drawille.py#L132) a point at (x, y), and a function to [give integer coordinates from float coordinates](https://github.com/asciimoo/drawille/blob/master/drawille.py#L82), and function to [get the character that contains a dot at the position (x, y)](https://github.com/asciimoo/drawille/blob/master/drawille.py#L82).

@wasamasa: Thank you for this overview of problematic and methods.  I will avoid to redraw everything by creating functions that only redraw the relevant character on the string.  I will need further intermediate virtual representation:

I did not used any virtualization of the characters, neither intermediate between the matrix and the final string.  I will not convert a matrix directly to a string, but rather to a matrix (2 levels) of vectors (3rd level) corresponding to a character, like this:

```elisp
[0 1
 1 0
 1 0
 0 1]
```
```elsip
(drawille-vector-to-char [0 1 1 0 1 0 0 1])
"⢎"
```
And then walk through the matrix and convert each of these vectors, and add a `"\n"` character at the end of a row.

This way, I will be able to retrieve what the character was at (x, y) without recalculating it from the original matrix, and then update the single character (the dot at (x, y) and the other dots of the matrix, retrieved from the intermediate matrix).

**Comment by hatschipuh** [comment]
I tried to make some fireworks like ascii animation with it: 
https://gist.github.com/hatschipuh/a4d235a1d5194fe63e21

**Comment by sshbio** [comment]
@hatschipuh: These will be useful, thank you!

Once I will have implemented a drawille update function, I will consider adding functions do draw dots, circles/ellipsis, squares/rectangles/polygons, lines/paths/curves/bezier, sparklines/plots (to apply a function), convert images...

But one at a time, of course.

**Comment by sshbio** [comment]
@hatschipuh: These will be useful, thank you!

Once I will have implemented a drawille update function, I will consider adding functions do draw dots, circles/ellipsis, squares/rectangles/polygons, lines/paths/curves/bezier, sparklines/plots (to apply a function), convert images...

But one at a time, of course.

**Comment by hatschipuh** [comment]
Sounds good :) Color support would be a funny feature as well, although you can only color one character at a time and not the individual dots.

**Comment by sshbio** [comment]
Yes, this could come after. 

Maybe blending the colors like I've seen in @bbatsov's [solarized theme](https://github.com/bbatsov/solarized-emacs/blob/master/solarized.el#L118-L153) or @abo-abo's [swiper package (colir.el)](https://github.com/bbatsov/solarized-emacs/blob/master/solarized.el#L118-L153).

**Comment by sshbio** [comment]
I added the essential functions so that all of the features I promised (but the colors and images) can be reallized (that is mostly geometry and not much programming anymore).

I still plan to add functions to produce them right away.

**Comment by wasamasa** [comment]
Colors wouldn't make much sense anyways, would they? Considering you're
using braille glyphs to increase resolution, coloring an individual glyph
would ruin the effect because the resolution is back to normal again.

Image support is tricky. The existing support is only good for displaying
them, you'd need a C module giving you the decoded pixels, shell out an
external process doing the hard work or write an elisp decoder for the heck
of it.

**Comment by sshbio** [comment]
Color support would require blending them for dots per character to preserve the resolution.
And there is no need of an emacs lisp image decoder, indeed.

Only remain the implementation of geometric shapes.

Maybe wipping points could be usefull as well...

**Comment by sshbio** [comment]
Image support was not that hard to implement, since emacs has ImageMagick as dependency.  
It can produce a [pbm](http://netpbm.sourceforge.net/doc/pbm.html) image:

```
P1
# feep.pbm
24 7
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 1 1 1 1 0 0 1 1 1 1 0 0 1 1 1 1 0 0 1 1 1 1 0
0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0
0 1 1 1 0 0 0 1 1 1 0 0 0 1 1 1 0 0 0 1 1 1 1 0
0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0
0 1 0 0 0 0 0 1 1 1 1 0 0 1 1 1 1 0 0 1 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
```

Also, this tools has plenty of options to optimize the visibility of the produced image (such as dithering, negate or levels).
